#!/usr/bin/env bash
# -------------------------------------------------------------
#  makecrandist.sh - creates the CRAN source tarball
#
#  Result:  triplclust_<version>.tar.gz
#
#  Everything happens in a temporary directory, so the
#  repository itself is never modified.
#
#  Depends on: R, Rcpp, roxygen2
# -------------------------------------------------------------
set -euo pipefail

SRCDIR=../src                     # where the C++ source of triplclust are
OLDDIR="$(pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT      # clean up tmpdir after sript ends
PKG="${WORK}/triplclust"         # temporary package

# ---------- Step 1: copy the R package ----------
mkdir -p "${PKG}"
cp -a * "${PKG}"


# ---------- Step 2: license ----------
# lic_cran (CRAN's short format) becomes the package LICENSE.
#cp LICENSE  "${PKG}"/inst/COPYRIGHTS
mv "${PKG}"/lic_cran "${PKG}"/LICENSE

# ---------- Step 3: copy the C++ sources ----------
cp -r ${SRCDIR}/hclust ${SRCDIR}/kdtree "${PKG}"/src/
cp ${SRCDIR}/*.cpp ${SRCDIR}/*.h "${PKG}"/src/


# These two are only needed for the standalone binary
cd "${PKG}"

# Remove files that do not belong into the CRAN package
rm -f makecrandist.sh verify.sh
#rm -f src/*.o src/*.so src/RcppExports.*
rm src/main.cpp src/option.cpp

# R compiles only the .cpp files directly in src/, so move them up.
# The fastcluster_*dm.cpp files stay in hclust/ because they are #included.
mv src/hclust/fastcluster.cpp src/
mv src/kdtree/kdtree.cpp src/


# ---------- Step 4: adapt the sources for CRAN ----------
# (a) remove warning-suppression pragmas
for f in src/*.cpp src/hclust/*.cpp; do
	sed '/^[[:space:]]*#pragma GCC diagnostic /d' "$f" >bla && mv bla "$f"
done
       

# (c) CRAN forbids std::cout / std::cerr: use Rcpp::Rcout instead
for f in $(grep -lE 'std::(cout|cerr)' src/*.cpp || true); do
  sed -E 's/std::(cout|cerr)/Rcpp::Rcout/g' "$f" >bla && mv bla "$f"
  sed '1i\
#include <Rcpp.h>\
' "$f" >bla && mv bla "$f"
done

# ---------- Step 5: generate Rcpp glue code and documentation ----------
# Rcpp requires NAMESPACE to recognize the package directory; the marker lets
# roxygen2 replace this placeholder with the generated namespace.
if [[ ! -f NAMESPACE ]]; then
  printf '%s\n' '# Generated by roxygen2: do not edit by hand' > NAMESPACE
fi
Rscript -e "Rcpp::compileAttributes('.')"
Rscript -e "roxygen2::roxygenise('.', roclets = c('namespace', 'collate', 'rd'))"

# ---------- Step 6: build the tarball ----------
cd "${WORK}"
R CMD build triplclust
mv triplclust_*.tar.gz "${OLDDIR}/"

echo "Tarball created in: ${OLDDIR}/"
